exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "feature/kurages"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: パソコミ
description: パソコミ
